version: '4.0'
services:
    web:
        platform: linux/amd64 # Explicitly set for TDX
        image: listerewan/based-agent-test:latest@sha256:a908584abf9ad91dd791fc628d598b6263c868df8d68ff96957bf9fd3473ca75
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
